spring.application.name=Email_demo

# =========================
# MySQL Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/email_demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Email Configuration
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= -- Enter your Email --
spring.mail.password=-- Enter your Password --

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# Swagger UI: http://localhost:8080/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8080 