spring.application.name=Spring_E_Com

# ===========================
# Server
# ===========================
server.port=8080

# ===========================
# Database
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===========================
# Email Configuration
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pradeeptaware081@gmail.com
spring.mail.password=kxwnnveqmgnucaqz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ===========================
# JWT Configuration
# ===========================
jwt.secret=aFRE7Luiy11Lyc6x9dY//1/SSAdub56LzmJyG7gOOgE=
jwt.expiration=86400000

# ===========================
# Swagger
# ===========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html