#spring.application.name=Spring12
#spring.datasource.url=jdbc:mysql://localhost:3306/order2
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## ---------- JPA / Hibernate ----------
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
## ---------- Swagger / OpenAPI ----------
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html

spring.profiles.active=${PROFILE:mysql}

#spring.profiles.active=h2
#spring.profiles.actice=neon