spring.application.name=Spring_Email_Security
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pradeeptaware081@gmail.com
spring.mail.password=tfbqbcflziwelngf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

spring.datasource.url=jdbc:mysql://localhost:3306/orderdb1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080